// <auto-generated />
using System;
using FileAnalysisService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FileAnalysisService.Migrations
{
    [DbContext(typeof(AnalysAppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FileAnalysisService.Data.AnalysisResult", b =>
                {
                    b.Property<Guid>("FileId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.HasKey("FileId");

                    b.ToTable("AnalysisResults");
                });

            modelBuilder.Entity("FileAnalysisService.Data.AnalysisResult", b =>
                {
                    b.OwnsOne("FileAnalysisService.Data.AnalysResult", "AnalysResults", b1 =>
                        {
                            b1.Property<Guid>("AnalysisResultFileId")
                                .HasColumnType("uuid");

                            b1.Property<int>("ParagraphCount")
                                .HasColumnType("integer");

                            b1.Property<int>("SymbolCount")
                                .HasColumnType("integer");

                            b1.Property<int>("WordCount")
                                .HasColumnType("integer");

                            b1.HasKey("AnalysisResultFileId");

                            b1.ToTable("AnalysisResults");

                            b1.WithOwner()
                                .HasForeignKey("AnalysisResultFileId");
                        });

                    b.Navigation("AnalysResults")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
